name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'destroy' to confirm"
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC Infra Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640344572675:role/github-infra-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: terraform

      # ✅ ✅ ADD IT HERE (IMPORTANT)
      - name: Validate input
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "destroy" ]; then
            echo "You must type 'destroy' to proceed"
            exit 1
          fi

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform